config/routes.rb
Rails.application.routes.draw do
  get 'chat_rooms/show'
  root 'home#index'

  resources :rooms do
    post 'add' => 'groups#create'
    delete '/add' => 'groups#destroy'
  end

  mount ActionCable.server => '/cable'
  # devise
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "sign_up", :to => "users/registrations#new"
    get "sign_in", :to => "users/sessions#new"
    delete "sign_out", :to => "users/sessions#destroy"
  end
  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users, through: :groups
  has_many :groups
  accepts_nested_attributes_for :groups
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms, through: :groups
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def show
    @chats = Chat.all
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def create
    user = current_user
    room = Room.find(params[:room_id])
    if Group.create(user_id: user.id, room_id: room.id)
      redirect_to rooms_path, notice: "#{room.title}にjoinしました"
    else
      redirect_to rooms_path
    end

  end

  def destroy
    user = current_user
    room = Room.find(params[:room_id])
    if group = Group.find_by(user_id: user.id, room_id: room.id)
      group.delete
      redirect_to rooms_path
    else
      redirect_to rooms_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    if current_user
      @rooms = Room.all
    else
      redirect_to root_path, notice: "ログインしてください"
    end
  end

  def show
    set_room
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path, notice: "ルーム「#{@room.title}」を登録しました。"
    else
      render :index, notice: "ルーム「#{@room.title}」を登録できませんでした。"
    end
  end

  def destroy
    set_room
    @room.destroy
    redirect_to rooms_path, notice: "投稿「#{@room.title}」を削除しました"
  end

  def edit
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:title, :detail)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/chat_rooms/show.html.erb
<h1>チャットルーム</h1>
<form class="form-inline">
  <div class="form-group">
    <input type="text" class="form-control" id="chat-input" />
  </div>
  <button id="button" class="btn btn-primary">送信</button>
</form>
<div id="messages">
  <%= render @chats %>
</div>

app/views/chats/_chat.html.erb
<li class="list-group-item">
  <p><%= chat.content %></p>
</li>

app/views/home/index.html.erb
<div class="background-image"></div>
<div class="home-body">
  <h1 class="home-title">アサカラにようこそ</h1>
  <p class="home-subtitle">ここでは同じ目標を持った人と、朝活ができます！</p>
  <p class="button-home"><%= link_to 'ルームにjoinしましょう！', rooms_path, class: "btn btn-success" %></p>
</div>

<%#
  <% if current_user %>
   <%# <%= form_for(current_user.rooms.build) do |f| %>
      <%# <%= f.label :"room登録" %>
     <%# <%= f.text_field :name, placeholder: "Room Name" %>
      <%#<%= f.submit "Registration" %>
    <%# <% end %>
  <%#<% end %>

app/views/rooms/_form.html.erb
<div class="container">
  <%= form_with model: @room do |f| %>
    <div class="form_group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', id: 'post_title' %>
    </div>
    <div class="form_group">
      <%= f.label :detail %>
      <%= f.text_area :detail, class: 'form-control', rows: "4", id: 'post_title' %>
    </div>
    <div class="form_group">
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<h1>Rooms#edit</h1>
<p>Find me in app/views/rooms/edit.html.erb</p>

app/views/rooms/index.html.erb
<h1>ルーム一覧</h1>
<p>あなたの興味のあるルームにジョインしましょう</p>

<% @rooms.each do |room| %>
  <ul>
    <li><%= link_to room.title, room_path(room) %></li>
    <% if !Group.exists?(user_id:current_user.id,room_id:room.id)%>
      <p><%= link_to '参加', room_add_path(room), method: :post, class: 'btn btn-success' %></p>
    <% else %>
      <p><%= link_to "退会",room_add_path(room), method: :delete, class: :'btn btn-danger' %></p>
    <% end %>
  </ul>

<% end %>
<%= link_to "新規追加", new_room_path, class: 'btn btn-primary' %>

app/views/rooms/new.html.erb
<h1>ルームの追加</h1>
<div class="nav justify-content-end">
  <%= link_to '一覧', rooms_path, class: 'nav-link' %>
  <%= render partial: 'form', locals: {room: @room} %>
</div>

app/views/rooms/show.html.erb
<h1>
  <%= @room.title %>
</h1>
<p>
  <%= @room.detail %>
</p>

<ul>
  <p>メンバー</p>
  <% @room.groups.each do |room_user| %>
  <li><%= room_user.user.name %></li>
  <% end %>
</ul>

<p><%= link_to 'チャットルーム', chat_rooms_show_path, class: "btn btn-primary" %></p>
<p><%= link_to '戻る', rooms_path %></p>
<p><%= link_to '削除', @room, method: :delete, data: { confirm: "タスク「#{@room.title}」を削除してもよろしいですか？"}, class: 'btn btn-danger' %></p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>